#!/bin/bash

load_inputs() {
    TODO_TREE_PATH="${INPUT_PATH:-.}"
    TODO_TREE_TAGS="${INPUT_TAGS:-}"
    TODO_TREE_INCLUDE_PATTERNS="${INPUT_INCLUDE_PATTERNS:-}"
    TODO_TREE_EXCLUDE_PATTERNS="${INPUT_EXCLUDE_PATTERNS:-}"
    TODO_TREE_CHANGED_ONLY="${INPUT_CHANGED_ONLY:-false}"
    TODO_TREE_NEW_ONLY="${INPUT_NEW_ONLY:-false}"
    TODO_TREE_FAIL_ON_TODOS="${INPUT_FAIL_ON_TODOS:-false}"
    TODO_TREE_FAIL_ON_FIXME="${INPUT_FAIL_ON_FIXME:-false}"
    TODO_TREE_MAX_TODOS="${INPUT_MAX_TODOS:-}"
    TODO_TREE_SHOW_ANNOTATIONS="${INPUT_SHOW_ANNOTATIONS:-true}"
    TODO_TREE_MAX_ANNOTATIONS="${INPUT_MAX_ANNOTATIONS:-50}"
    TODO_TREE_GITHUB_BASE_REF="${GITHUB_BASE_REF:-main}"
    TODO_TREE_GITHUB_HEAD_REF="${GITHUB_HEAD_REF:-HEAD}"
}
